name: Build STM32 Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ARM GCC Toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi

    - name: Build firmware
      run: |
        mkdir -p build
        arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -Wall -O2 Core/Src/*.c -o build/firmware.elf -ICore/Inc
        arm-none-eabi-objcopy -O binary build/firmware.elf build/firmware.bin

    - name: Upload .bin file
      uses: actions/upload-artifact@v3.1.2
      with:
        name: firmware-bin
        path: build/firmware.bin
